### ISSUE TITLE
Fail to build on v1.0.4 because of filure to make client.go

### ISSUE THREAD

**Issue by georgekcchung** [orzhaha/cassandra-web#10]
as title.

I can build it on v1.0.3 but not v1.0.4 as client.go cannot be built.

~/go/bin/go-bindata -o=client/client.go -pkg=client client/dist/...
bindata: Failed to stat input path 'client/dist': lstat client/dist: no such file or directory

**Comment by kfrico** [comment]
you should cd /go/src/cassandra-web/client && npm i && npm run build
