### ISSUE TITLE
Feature request: Support multiple Cassandra nodes

### ISSUE THREAD

**Issue by acolombier** [orzhaha/cassandra-web#15]
In order to support the non-single point of failure feature of Cassandra, it would be great if we could pass a list of host (perhaps a string comma-separated?). I can see that `NewCluster` is a variadic function so I believe this shouldn't be too complicated. If you wish, I'm happy to submit a PR although my experience with Golang is close to null ;)

https://github.com/orzhaha/cassandra-web/blob/cb49579f59bcfe11cf6609a6412583d7c0eed6a3/service/main.go#L123

**Comment by kfrico** [comment]
https://github.com/orzhaha/cassandra-web/commit/1f5a8b0e78968383672cacba68b631c7945acc48

**Comment by acolombier** [comment]
That was very efficient! Thanks a lot
