### ISSUE TITLE
Read Only View And Read Write view

### ISSUE THREAD

**Issue by containeers** [orzhaha/cassandra-web#17]
At present, it only shows a read-write view. Can we have a user interface with read-only option?

**Comment by kfrico** [comment]
you can use role

https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/cqlCreateRole.html

**Comment by mzaghab** [comment]
it's a good idea to give an option to give a readonly view of the UI (remove all drop/modify button, drop keyspace, drop table, modify data ....)

**Comment by kfrico** [comment]
Do you want to avoid user from touching the view of UI accidentally or just try to authority control?

**Comment by mzaghab** [comment]
as we have a cassandra cluster without auth enabled, so we can't use the cassandra role to limit the user ACL, may be a solution is to give an option at the application lauch (for example) to hide all button that can modify the database object and data (button modify, delete, import ....)

**Comment by kfrico** [comment]
https://github.com/orzhaha/cassandra-web/commit/aa8526b9b271322ec75cd1dc240f31e74a99cf4f
