### ISSUE TITLE
Edit/Delete has problem with strings containing numbers containing leading zeros

### ISSUE THREAD

**Issue by drej1** [orzhaha/cassandra-web#39]
Hi, there is an issue while editing/deleting rows where the part of the id is a string containing a number with leading zero(s).

We have a following table
```sql
create table dps_usage_consumption.evs_to_acc
(
    event_source   text,
    account_num    text,
    bill_event_seq int,
    last_bill_date date,
    next_bill_date date,
    primary key (event_source, account_num)
)
```

event_source may contain msisdns in international format, like 00421xxxxxxxxx
Unfortunately, when you edit/delete such a row it sends request where the event_source is without leading zeros, like:

`{"item":"{\"event_source\":421949323548,\"account_num\":3107413306,\"bill_event_seq\":43,\"last_bill_date\":\"2023-02-01\",\"next_bill_date\":\"2023-02-01\"}","table":"dps_usage_consumption.evs_to_acc"}`

<img width="1288" alt="image" src="https://github.com/orzhaha/cassandra-web/assets/31669116/c45f6828-078c-41dc-8640-7ef1cb65b1cc">

I assume it's the problem in method 
```javascript
jsonParams(jsonString) {
      try {
        return JSONbig.parse(jsonString)
      } catch (e) {
        return jsonString
      }
    }
```

I assume if you send there **00**421949323548, the leading zeros are ommited and you get 421949323548.

Can you please look into this? Maybe you should take into account the cassandra types. It's text here, so it shpould be treated as string instead of trying to make it into a bigint.

Thank You

**Comment by kfrico** [comment]
fix [284cf9a](https://github.com/orzhaha/cassandra-web/commit/284cf9a56115cb91162b20f3c00c3dbd6a82d13b)
