### ISSUE TITLE
table describe(definition) method returned error code 500 in cassandra-web ui

### ISSUE THREAD

**Issue by userfromla** [orzhaha/cassandra-web#46]
@kfrico @lin-yen @lwille :

error:
{ "body": { "message": "exit status 2" }, "debug": { "original": null, "response": { "req": { "method": "GET", "url": "describe?table=billboard.billboard_detail", "headers": {} }, "xhr": {}, "text": "{\"message\":\"exit status 2\"}\n", "statusText": "", "statusCode": 500, "status": 500, "statusType": 5, "info": false, "ok": false, "redirect": false, "clientError": false, "serverError": true, "error": { "status": 500, "method": "GET", "url": "describe?table=billboard.billboard_detail" }, "accepted": false, "noContent": false, "badRequest": false, "unauthorized": false, "notAcceptable": false, "forbidden": false, "notFound": false, "headers": { "content-length": "28", "content-type": "application/json; charset=UTF-8", "date": "Fri, 02 Aug 2024 11:39:44 GMT", "strict-transport-security": "max-age=15724800; includeSubDomains" }, "header": { "content-length": "28", "content-type": "application/json; charset=UTF-8", "date": "Fri, 02 Aug 2024 11:39:44 GMT", "strict-transport-security": "max-age=15724800; includeSubDomains" }, "type": "application/json", "charset": "UTF-8", "links": {}, "body": { "message": "exit status 2" } }, "status": 500 }, "status": 500, "statusText": "", "text": "{\"message\":\"exit status 2\"}\n", "error": {} }

As I found out, the reason for this error in cassandra web ui (when I want to view "definition" of table) is that the properties of the table contain a comment in a language that contains letters not only of the Latin alphabet (for example, Swedish), see the details below.

For example describe function of my table (result of request in cqlsh):

CREATE TABLE billboard.billboard_detail (
    performer_id bigint,
    performer_alias text,
    performer_description text,
    PRIMARY KEY (performer_id, performer_alias)
) WITH CLUSTERING ORDER BY (performer_alias ASC)
    AND additional_write_policy = '99p'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = 'en lista över kommande händelser'
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '16', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99p';

As you can see, the comment contains not only Latin letters.
However, if I remove non-Latin letters or leave the field "comment" empty, there will be no error code 500 when accessing the function "definition" in cassandra-web ui.

For the purpose of checking, I added support Swedish language by installing locale sv_SE.UTF-8 in the docker container and as a result, the locale command returns:
LANG=sv_SE.UTF-8
LC_CTYPE=sv_SE.UTF-8
LC_NUMERIC=sv_SE.UTF-8
LC_TIME=sv_SE.UTF-8
LC_COLLATE=sv_SE.UTF-8
LC_MONETARY=sv_SE.UTF-8
LC_MESSAGES=sv_SE.UTF-8
LC_ALL=sv_SE.UTF-8

But it had no effect on error .
As far as I understand, changes should be made in your src files.

Can you fix the error? 
Or explain what changes need to be made so that there are no problems when using not only Latin letters in comment properties of table.

Thank you.

P/S
It seems to me that there has been a message about this error before, but without details
https://github.com/orzhaha/cassandra-web/issues/22

**Comment by kfrico** [comment]
Thank you for your suggestions; they have been addressed in the latest version. [v1.1.5](https://github.com/orzhaha/cassandra-web/releases/tag/v1.1.5)

**Comment by userfromla** [comment]
@kfrico , thank you very much, now works correctly with non-Latin letters
